version: 1.2
workflows:
  - name: nobias_metrics
    subclass: WDL
    primaryDescriptorPath: /anvil/modeling/nobias_metrics/nobias_metrics.wdl
    publish: true
    authors:
      - name: Vivekanandan Ramalingam
        email: vir@stanford.edu
  - name: modelling_bias0
    subclass: WDL
    primaryDescriptorPath: /anvil/modeling/nobias_metrics/run_modelling_bias0.wdl
    publish: true
    authors:
      - name: Vivekanandan Ramalingam
        email: vir@stanford.edu
