apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: mypod
    image: centos
    resources:
      limits:
        memory: 100Mi
        cpu: 100m
      requests:
        memory: 100Mi
        cpu: 100m
    command: ["sh", "-c", "echo 'Im a new pod' && sleep infinity"]
    volumeMounts:
    - name: tf-atlas
      mountPath: /mydata
  restartPolicy: Never
  volumes:
    - name: tf-atlas
      persistentVolumeClaim:
        claimName: tf-atlas